/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "authentication.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemInfo, SystemInfo, 2)


PB_BIND(LoginCredentials, LoginCredentials, 2)


PB_BIND(ClientResponseEncrypted, ClientResponseEncrypted, 2)


PB_BIND(APWelcome, APWelcome, 2)


PB_BIND(AccountInfo, AccountInfo, AUTO)


PB_BIND(AccountInfoSpotify, AccountInfoSpotify, AUTO)


PB_BIND(AccountInfoFacebook, AccountInfoFacebook, AUTO)







