/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "keyexchange.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoginCryptoDiffieHellmanChallenge, LoginCryptoDiffieHellmanChallenge, AUTO)


PB_BIND(LoginCryptoChallengeUnion, LoginCryptoChallengeUnion, AUTO)


PB_BIND(LoginCryptoDiffieHellmanHello, LoginCryptoDiffieHellmanHello, AUTO)


PB_BIND(LoginCryptoHelloUnion, LoginCryptoHelloUnion, AUTO)


PB_BIND(BuildInfo, BuildInfo, AUTO)


PB_BIND(FeatureSet, FeatureSet, AUTO)


PB_BIND(APChallenge, APChallenge, AUTO)


PB_BIND(APResponseMessage, APResponseMessage, AUTO)


PB_BIND(LoginCryptoDiffieHellmanResponse, LoginCryptoDiffieHellmanResponse, AUTO)


PB_BIND(LoginCryptoResponseUnion, LoginCryptoResponseUnion, AUTO)


PB_BIND(CryptoResponseUnion, CryptoResponseUnion, AUTO)


PB_BIND(PoWResponseUnion, PoWResponseUnion, AUTO)


PB_BIND(ClientResponsePlaintext, ClientResponsePlaintext, AUTO)


PB_BIND(ClientHello, ClientHello, 2)






