/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "metadata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AudioFile, AudioFile, AUTO)


PB_BIND(Restriction, Restriction, AUTO)


PB_BIND(Image, Image, AUTO)


PB_BIND(ImageGroup, ImageGroup, AUTO)


PB_BIND(Album, Album, AUTO)


PB_BIND(Artist, Artist, AUTO)


PB_BIND(Track, Track, AUTO)


PB_BIND(Episode, Episode, 2)




